/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const AppUninstalledEventEvent = {
  AppUninstalled: "app.uninstalled",
} as const;
export type AppUninstalledEventEvent = ClosedEnum<
  typeof AppUninstalledEventEvent
>;

/**
 * App Uninstalled Event
 */
export type AppUninstalledEventRequestBody = {
  /**
   * Information about the app
   */
  data: components.AppInstall;
  /**
   * Unix timestamp representing when the event was created
   */
  created: number;
  event: AppUninstalledEventEvent;
};

/** @internal */
export const AppUninstalledEventEvent$inboundSchema: z.ZodNativeEnum<
  typeof AppUninstalledEventEvent
> = z.nativeEnum(AppUninstalledEventEvent);
/** @internal */
export const AppUninstalledEventEvent$outboundSchema: z.ZodNativeEnum<
  typeof AppUninstalledEventEvent
> = AppUninstalledEventEvent$inboundSchema;

/** @internal */
export const AppUninstalledEventRequestBody$inboundSchema: z.ZodType<
  AppUninstalledEventRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: components.AppInstall$inboundSchema,
  created: z.number().int(),
  event: AppUninstalledEventEvent$inboundSchema,
});
/** @internal */
export type AppUninstalledEventRequestBody$Outbound = {
  data: components.AppInstall$Outbound;
  created: number;
  event: string;
};

/** @internal */
export const AppUninstalledEventRequestBody$outboundSchema: z.ZodType<
  AppUninstalledEventRequestBody$Outbound,
  z.ZodTypeDef,
  AppUninstalledEventRequestBody
> = z.object({
  data: components.AppInstall$outboundSchema,
  created: z.number().int(),
  event: AppUninstalledEventEvent$outboundSchema,
});

export function appUninstalledEventRequestBodyToJSON(
  appUninstalledEventRequestBody: AppUninstalledEventRequestBody,
): string {
  return JSON.stringify(
    AppUninstalledEventRequestBody$outboundSchema.parse(
      appUninstalledEventRequestBody,
    ),
  );
}
export function appUninstalledEventRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<AppUninstalledEventRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppUninstalledEventRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppUninstalledEventRequestBody' from JSON`,
  );
}
