/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CheckinDeletedEventData = {
  id: string;
  /**
   * Unique identifier for the customer
   */
  customerId: string;
  /**
   * Unique identifier for the company the checkin was deleted from
   */
  companyId: string;
};

export const CheckinDeletedEventEvent = {
  CheckinDeleted: "checkin.deleted",
} as const;
export type CheckinDeletedEventEvent = ClosedEnum<
  typeof CheckinDeletedEventEvent
>;

/**
 * Checkin Deleted Event
 */
export type CheckinDeletedEventRequestBody = {
  data: CheckinDeletedEventData;
  /**
   * Unix timestamp representing when the event was created
   */
  created: number;
  event: CheckinDeletedEventEvent;
};

/** @internal */
export const CheckinDeletedEventData$inboundSchema: z.ZodType<
  CheckinDeletedEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customerId: z.string(),
  companyId: z.string(),
});
/** @internal */
export type CheckinDeletedEventData$Outbound = {
  id: string;
  customerId: string;
  companyId: string;
};

/** @internal */
export const CheckinDeletedEventData$outboundSchema: z.ZodType<
  CheckinDeletedEventData$Outbound,
  z.ZodTypeDef,
  CheckinDeletedEventData
> = z.object({
  id: z.string(),
  customerId: z.string(),
  companyId: z.string(),
});

export function checkinDeletedEventDataToJSON(
  checkinDeletedEventData: CheckinDeletedEventData,
): string {
  return JSON.stringify(
    CheckinDeletedEventData$outboundSchema.parse(checkinDeletedEventData),
  );
}
export function checkinDeletedEventDataFromJSON(
  jsonString: string,
): SafeParseResult<CheckinDeletedEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckinDeletedEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckinDeletedEventData' from JSON`,
  );
}

/** @internal */
export const CheckinDeletedEventEvent$inboundSchema: z.ZodNativeEnum<
  typeof CheckinDeletedEventEvent
> = z.nativeEnum(CheckinDeletedEventEvent);
/** @internal */
export const CheckinDeletedEventEvent$outboundSchema: z.ZodNativeEnum<
  typeof CheckinDeletedEventEvent
> = CheckinDeletedEventEvent$inboundSchema;

/** @internal */
export const CheckinDeletedEventRequestBody$inboundSchema: z.ZodType<
  CheckinDeletedEventRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CheckinDeletedEventData$inboundSchema),
  created: z.number().int(),
  event: CheckinDeletedEventEvent$inboundSchema,
});
/** @internal */
export type CheckinDeletedEventRequestBody$Outbound = {
  data: CheckinDeletedEventData$Outbound;
  created: number;
  event: string;
};

/** @internal */
export const CheckinDeletedEventRequestBody$outboundSchema: z.ZodType<
  CheckinDeletedEventRequestBody$Outbound,
  z.ZodTypeDef,
  CheckinDeletedEventRequestBody
> = z.object({
  data: z.lazy(() => CheckinDeletedEventData$outboundSchema),
  created: z.number().int(),
  event: CheckinDeletedEventEvent$outboundSchema,
});

export function checkinDeletedEventRequestBodyToJSON(
  checkinDeletedEventRequestBody: CheckinDeletedEventRequestBody,
): string {
  return JSON.stringify(
    CheckinDeletedEventRequestBody$outboundSchema.parse(
      checkinDeletedEventRequestBody,
    ),
  );
}
export function checkinDeletedEventRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CheckinDeletedEventRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckinDeletedEventRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckinDeletedEventRequestBody' from JSON`,
  );
}
