/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CheckinDeletedEventEvent = {
  CheckinDeleted: "checkin.deleted",
} as const;
export type CheckinDeletedEventEvent = ClosedEnum<
  typeof CheckinDeletedEventEvent
>;

/**
 * Checkin Deleted Event (Not implemented)
 */
export type CheckinDeletedEventRequestBody = {
  /**
   * Checkin for a class, event, appointment or an open facility
   */
  data: components.Checkin;
  /**
   * Unix timestamp representing when the event was created
   */
  created: number;
  event: CheckinDeletedEventEvent;
};

/** @internal */
export const CheckinDeletedEventEvent$inboundSchema: z.ZodNativeEnum<
  typeof CheckinDeletedEventEvent
> = z.nativeEnum(CheckinDeletedEventEvent);

/** @internal */
export const CheckinDeletedEventEvent$outboundSchema: z.ZodNativeEnum<
  typeof CheckinDeletedEventEvent
> = CheckinDeletedEventEvent$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckinDeletedEventEvent$ {
  /** @deprecated use `CheckinDeletedEventEvent$inboundSchema` instead. */
  export const inboundSchema = CheckinDeletedEventEvent$inboundSchema;
  /** @deprecated use `CheckinDeletedEventEvent$outboundSchema` instead. */
  export const outboundSchema = CheckinDeletedEventEvent$outboundSchema;
}

/** @internal */
export const CheckinDeletedEventRequestBody$inboundSchema: z.ZodType<
  CheckinDeletedEventRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: components.Checkin$inboundSchema,
  created: z.number().int(),
  event: CheckinDeletedEventEvent$inboundSchema,
});

/** @internal */
export type CheckinDeletedEventRequestBody$Outbound = {
  data: components.Checkin$Outbound;
  created: number;
  event: string;
};

/** @internal */
export const CheckinDeletedEventRequestBody$outboundSchema: z.ZodType<
  CheckinDeletedEventRequestBody$Outbound,
  z.ZodTypeDef,
  CheckinDeletedEventRequestBody
> = z.object({
  data: components.Checkin$outboundSchema,
  created: z.number().int(),
  event: CheckinDeletedEventEvent$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckinDeletedEventRequestBody$ {
  /** @deprecated use `CheckinDeletedEventRequestBody$inboundSchema` instead. */
  export const inboundSchema = CheckinDeletedEventRequestBody$inboundSchema;
  /** @deprecated use `CheckinDeletedEventRequestBody$outboundSchema` instead. */
  export const outboundSchema = CheckinDeletedEventRequestBody$outboundSchema;
  /** @deprecated use `CheckinDeletedEventRequestBody$Outbound` instead. */
  export type Outbound = CheckinDeletedEventRequestBody$Outbound;
}

export function checkinDeletedEventRequestBodyToJSON(
  checkinDeletedEventRequestBody: CheckinDeletedEventRequestBody,
): string {
  return JSON.stringify(
    CheckinDeletedEventRequestBody$outboundSchema.parse(
      checkinDeletedEventRequestBody,
    ),
  );
}

export function checkinDeletedEventRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CheckinDeletedEventRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckinDeletedEventRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckinDeletedEventRequestBody' from JSON`,
  );
}
