/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import * as components from "../components/index.js";

export const CustomerUpdatedEventEventType = {
  Updated: "updated",
} as const;
export type CustomerUpdatedEventEventType = ClosedEnum<
  typeof CustomerUpdatedEventEventType
>;

export type CustomerUpdatedEventRequestBody = {
  /**
   * Schema representing a customer, former customer or lead served by Company
   */
  data: components.Customer;
  /**
   * Unix timestamp of the update event
   */
  created: number;
  eventType: CustomerUpdatedEventEventType;
};

/** @internal */
export const CustomerUpdatedEventEventType$inboundSchema: z.ZodNativeEnum<
  typeof CustomerUpdatedEventEventType
> = z.nativeEnum(CustomerUpdatedEventEventType);

/** @internal */
export const CustomerUpdatedEventEventType$outboundSchema: z.ZodNativeEnum<
  typeof CustomerUpdatedEventEventType
> = CustomerUpdatedEventEventType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerUpdatedEventEventType$ {
  /** @deprecated use `CustomerUpdatedEventEventType$inboundSchema` instead. */
  export const inboundSchema = CustomerUpdatedEventEventType$inboundSchema;
  /** @deprecated use `CustomerUpdatedEventEventType$outboundSchema` instead. */
  export const outboundSchema = CustomerUpdatedEventEventType$outboundSchema;
}

/** @internal */
export const CustomerUpdatedEventRequestBody$inboundSchema: z.ZodType<
  CustomerUpdatedEventRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: components.Customer$inboundSchema,
  created: z.number().int(),
  eventType: CustomerUpdatedEventEventType$inboundSchema,
});

/** @internal */
export type CustomerUpdatedEventRequestBody$Outbound = {
  data: components.Customer$Outbound;
  created: number;
  eventType: string;
};

/** @internal */
export const CustomerUpdatedEventRequestBody$outboundSchema: z.ZodType<
  CustomerUpdatedEventRequestBody$Outbound,
  z.ZodTypeDef,
  CustomerUpdatedEventRequestBody
> = z.object({
  data: components.Customer$outboundSchema,
  created: z.number().int(),
  eventType: CustomerUpdatedEventEventType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerUpdatedEventRequestBody$ {
  /** @deprecated use `CustomerUpdatedEventRequestBody$inboundSchema` instead. */
  export const inboundSchema = CustomerUpdatedEventRequestBody$inboundSchema;
  /** @deprecated use `CustomerUpdatedEventRequestBody$outboundSchema` instead. */
  export const outboundSchema = CustomerUpdatedEventRequestBody$outboundSchema;
  /** @deprecated use `CustomerUpdatedEventRequestBody$Outbound` instead. */
  export type Outbound = CustomerUpdatedEventRequestBody$Outbound;
}
