/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CustomerUpdatedEventEvent = {
  CustomerUpdated: "customer.updated",
} as const;
export type CustomerUpdatedEventEvent = ClosedEnum<
  typeof CustomerUpdatedEventEvent
>;

/**
 * Customer Updated Event (Not implemented)
 */
export type CustomerUpdatedEventRequestBody = {
  /**
   * Schema representing a customer, former customer, or lead served by the company
   */
  data: components.Customer;
  /**
   * Schema representing a customer, former customer, or lead served by the company
   */
  previousValues?: components.Customer | undefined;
  /**
   * Unix timestamp representing when the event was created
   */
  created: number;
  event: CustomerUpdatedEventEvent;
};

/** @internal */
export const CustomerUpdatedEventEvent$inboundSchema: z.ZodNativeEnum<
  typeof CustomerUpdatedEventEvent
> = z.nativeEnum(CustomerUpdatedEventEvent);

/** @internal */
export const CustomerUpdatedEventEvent$outboundSchema: z.ZodNativeEnum<
  typeof CustomerUpdatedEventEvent
> = CustomerUpdatedEventEvent$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerUpdatedEventEvent$ {
  /** @deprecated use `CustomerUpdatedEventEvent$inboundSchema` instead. */
  export const inboundSchema = CustomerUpdatedEventEvent$inboundSchema;
  /** @deprecated use `CustomerUpdatedEventEvent$outboundSchema` instead. */
  export const outboundSchema = CustomerUpdatedEventEvent$outboundSchema;
}

/** @internal */
export const CustomerUpdatedEventRequestBody$inboundSchema: z.ZodType<
  CustomerUpdatedEventRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: components.Customer$inboundSchema,
  previousValues: components.Customer$inboundSchema.optional(),
  created: z.number().int(),
  event: CustomerUpdatedEventEvent$inboundSchema,
});

/** @internal */
export type CustomerUpdatedEventRequestBody$Outbound = {
  data: components.Customer$Outbound;
  previousValues?: components.Customer$Outbound | undefined;
  created: number;
  event: string;
};

/** @internal */
export const CustomerUpdatedEventRequestBody$outboundSchema: z.ZodType<
  CustomerUpdatedEventRequestBody$Outbound,
  z.ZodTypeDef,
  CustomerUpdatedEventRequestBody
> = z.object({
  data: components.Customer$outboundSchema,
  previousValues: components.Customer$outboundSchema.optional(),
  created: z.number().int(),
  event: CustomerUpdatedEventEvent$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerUpdatedEventRequestBody$ {
  /** @deprecated use `CustomerUpdatedEventRequestBody$inboundSchema` instead. */
  export const inboundSchema = CustomerUpdatedEventRequestBody$inboundSchema;
  /** @deprecated use `CustomerUpdatedEventRequestBody$outboundSchema` instead. */
  export const outboundSchema = CustomerUpdatedEventRequestBody$outboundSchema;
  /** @deprecated use `CustomerUpdatedEventRequestBody$Outbound` instead. */
  export type Outbound = CustomerUpdatedEventRequestBody$Outbound;
}

export function customerUpdatedEventRequestBodyToJSON(
  customerUpdatedEventRequestBody: CustomerUpdatedEventRequestBody,
): string {
  return JSON.stringify(
    CustomerUpdatedEventRequestBody$outboundSchema.parse(
      customerUpdatedEventRequestBody,
    ),
  );
}

export function customerUpdatedEventRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CustomerUpdatedEventRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerUpdatedEventRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerUpdatedEventRequestBody' from JSON`,
  );
}
