/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CustomerDeletedEventData = {
  /**
   * Unique identifier for the customer
   */
  id: string;
  /**
   * Unique identifier for the company the customer is in
   */
  companyId: string;
};

export const CustomerDeletedEventEvent = {
  CustomerDeleted: "customer.deleted",
} as const;
export type CustomerDeletedEventEvent = ClosedEnum<
  typeof CustomerDeletedEventEvent
>;

/**
 * Customer Deleted Event
 */
export type CustomerDeletedEventRequestBody = {
  data: CustomerDeletedEventData;
  /**
   * Unix timestamp representing when the event was created
   */
  created: number;
  event: CustomerDeletedEventEvent;
};

/** @internal */
export const CustomerDeletedEventData$inboundSchema: z.ZodType<
  CustomerDeletedEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  companyId: z.string(),
});
/** @internal */
export type CustomerDeletedEventData$Outbound = {
  id: string;
  companyId: string;
};

/** @internal */
export const CustomerDeletedEventData$outboundSchema: z.ZodType<
  CustomerDeletedEventData$Outbound,
  z.ZodTypeDef,
  CustomerDeletedEventData
> = z.object({
  id: z.string(),
  companyId: z.string(),
});

export function customerDeletedEventDataToJSON(
  customerDeletedEventData: CustomerDeletedEventData,
): string {
  return JSON.stringify(
    CustomerDeletedEventData$outboundSchema.parse(customerDeletedEventData),
  );
}
export function customerDeletedEventDataFromJSON(
  jsonString: string,
): SafeParseResult<CustomerDeletedEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerDeletedEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerDeletedEventData' from JSON`,
  );
}

/** @internal */
export const CustomerDeletedEventEvent$inboundSchema: z.ZodNativeEnum<
  typeof CustomerDeletedEventEvent
> = z.nativeEnum(CustomerDeletedEventEvent);
/** @internal */
export const CustomerDeletedEventEvent$outboundSchema: z.ZodNativeEnum<
  typeof CustomerDeletedEventEvent
> = CustomerDeletedEventEvent$inboundSchema;

/** @internal */
export const CustomerDeletedEventRequestBody$inboundSchema: z.ZodType<
  CustomerDeletedEventRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CustomerDeletedEventData$inboundSchema),
  created: z.number().int(),
  event: CustomerDeletedEventEvent$inboundSchema,
});
/** @internal */
export type CustomerDeletedEventRequestBody$Outbound = {
  data: CustomerDeletedEventData$Outbound;
  created: number;
  event: string;
};

/** @internal */
export const CustomerDeletedEventRequestBody$outboundSchema: z.ZodType<
  CustomerDeletedEventRequestBody$Outbound,
  z.ZodTypeDef,
  CustomerDeletedEventRequestBody
> = z.object({
  data: z.lazy(() => CustomerDeletedEventData$outboundSchema),
  created: z.number().int(),
  event: CustomerDeletedEventEvent$outboundSchema,
});

export function customerDeletedEventRequestBodyToJSON(
  customerDeletedEventRequestBody: CustomerDeletedEventRequestBody,
): string {
  return JSON.stringify(
    CustomerDeletedEventRequestBody$outboundSchema.parse(
      customerDeletedEventRequestBody,
    ),
  );
}
export function customerDeletedEventRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CustomerDeletedEventRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerDeletedEventRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerDeletedEventRequestBody' from JSON`,
  );
}
