/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { checkinsClassList } from "../../funcs/checkinsClassList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListClassCheckinsRequest$inboundSchema,
};

export const tool$checkinsClassList: ToolDefinition<typeof args> = {
  name: "checkins-class-list",
  description: `List Class Checkins

list event checkins`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await checkinsClassList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
