/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesList } from "../../funcs/classesList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListClassesRequest$inboundSchema,
};

export const tool$classesList: ToolDefinition<typeof args> = {
  name: "classes-list",
  description: `List Classes

Get a paginated list of classes`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await classesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
