/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersAttributionsList } from "../../funcs/customersAttributionsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListAttributionsRequest$inboundSchema,
};

export const tool$customersAttributionsList: ToolDefinition<typeof args> = {
  name: "customers-attributions-list",
  description: `List customer attributions

List customer attributions, optionally filtering by customer id and/or attribution event`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersAttributionsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
