/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { enrollmentGet } from "../../funcs/enrollmentGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetEnrollmentRequest$inboundSchema,
};

export const tool$enrollmentGet: ToolDefinition<typeof args> = {
  name: "enrollment-get",
  description: `Get Plan Enrollment Details

Get the enrollment details for the provided enrollment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await enrollmentGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
