/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { manageWebhooksUpdate } from "../../funcs/manageWebhooksUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateWebhookRequest$inboundSchema,
};

export const tool$manageWebhooksUpdate: ToolDefinition<typeof args> = {
  name: "manage-webhooks-update",
  description: `Update a Webhook

Update the details for a platform webhook including the signing secret an event subscriptions`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await manageWebhooksUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
