/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { manageWebhooksList } from "../../funcs/manageWebhooksList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListWebhooksRequest$inboundSchema,
};

export const tool$manageWebhooksList: ToolDefinition<typeof args> = {
  name: "manage-webhooks-list",
  description: `List Webhooks

List platform webhooks for the current customer, including the signing secret and event subscriptions`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await manageWebhooksList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
