/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { manageWebhooksActivate } from "../../funcs/manageWebhooksActivate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ActivateWebhookRequest$inboundSchema,
};

export const tool$manageWebhooksActivate: ToolDefinition<typeof args> = {
  name: "manage-webhooks-activate",
  description: `Activate a Webhook

Activate a deleted platform webhook`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await manageWebhooksActivate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
