/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesSmsSend } from "../../funcs/messagesSmsSend.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SendSmsRequest$inboundSchema,
};

export const tool$messagesSmsSend: ToolDefinition<typeof args> = {
  name: "messages-sms-send",
  description: `Send an SMS

Send an SMS message from the PushPress platform. Note that only first party apps can send SMS messages`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesSmsSend(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
