/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesPushSend } from "../../funcs/messagesPushSend.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SendPushRequest$inboundSchema,
};

export const tool$messagesPushSend: ToolDefinition<typeof args> = {
  name: "messages-push-send",
  description: `Send Push Notification

Send a push notification message from the PushPress platform. Note that only first party apps can send push notifications`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesPushSend(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
