/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reservationsList } from "../../funcs/reservationsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListReservationsRequest$inboundSchema,
};

export const tool$reservationsList: ToolDefinition<typeof args> = {
  name: "reservations-list",
  description: `List Reservations

Get a paginated list of reservations for a scheduled calendar event`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await reservationsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
