/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reservationsGet } from "../../funcs/reservationsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetReservationRequest$inboundSchema,
};

export const tool$reservationsGet: ToolDefinition<typeof args> = {
  name: "reservations-get",
  description: `Get Details for a Reservation

Get details for a reservation by its UUID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await reservationsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
