/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classCheckinsGet } from "../funcs/classCheckinsGet.js";
import { classCheckinsList } from "../funcs/classCheckinsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class ClassCheckins extends ClientSDK {
  /**
   * Get an event checkin
   */
  async get(
    request: operations.GetClassCheckinRequest,
    options?: RequestOptions,
  ): Promise<components.ClassCheckin> {
    return unwrapAsync(classCheckinsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a list of class checkins
   *
   * @remarks
   * list event checkins
   */
  async list(
    request: operations.ListClassCheckinsRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListClassCheckinsResponse>> {
    return unwrapResultIterator(classCheckinsList(
      this,
      request,
      options,
    ));
  }
}
