/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { enrollmentGet } from "../funcs/enrollmentGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Enrollment extends ClientSDK {
  /**
   * Get Plan Enrollment Details
   *
   * @remarks
   * Get the enrollment details for the provided enrollment
   */
  async get(
    request: operations.GetEnrollmentRequest,
    options?: RequestOptions,
  ): Promise<components.Enrollment> {
    return unwrapAsync(enrollmentGet(
      this,
      request,
      options,
    ));
  }
}
