/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { keysGet } from "../funcs/keysGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Keys extends ClientSDK {
  /**
   * Retrieve a single API key
   *
   * @remarks
   * Retrieve a single API key.
   */
  async get(
    request: operations.GetApiKeyRequest,
    options?: RequestOptions,
  ): Promise<components.ApiKey> {
    return unwrapAsync(keysGet(
      this,
      request,
      options,
    ));
  }
}
