/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesEmailSend } from "../funcs/messagesEmailSend.js";
import { messagesSmsSend } from "../funcs/messagesSmsSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Notifications } from "./notifications.js";
import { Push } from "./push.js";

export class Messages extends ClientSDK {
  private _notifications?: Notifications;
  get notifications(): Notifications {
    return (this._notifications ??= new Notifications(this._options));
  }

  private _push?: Push;
  get push(): Push {
    return (this._push ??= new Push(this._options));
  }

  /**
   * Send an email
   *
   * @remarks
   * Send an email from the PushPress platform
   */
  async emailSend(
    request: operations.SendEmailRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(messagesEmailSend(
      this,
      request,
      options,
    ));
  }

  /**
   * Send an SMS
   *
   * @remarks
   * Send an SMS message from the PushPress platform
   */
  async smsSend(
    request: operations.SendSmsRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(messagesSmsSend(
      this,
      request,
      options,
    ));
  }
}
