/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reservationsGet } from "../funcs/reservationsGet.js";
import { reservationsList } from "../funcs/reservationsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Reservations extends ClientSDK {
  /**
   * List Reservations
   *
   * @remarks
   * Get a paginated list of reservations for a scheduled calendar event
   */
  async list(
    request: operations.ListReservationsRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListReservationsResponse, { page: number }>
  > {
    return unwrapResultIterator(reservationsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Details for a Reservation
   *
   * @remarks
   * Get details for a reservation by its UUID
   */
  async get(
    request: operations.GetReservationRequest,
    options?: RequestOptions,
  ): Promise<components.Reservation> {
    return unwrapAsync(reservationsGet(
      this,
      request,
      options,
    ));
  }
}
