/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesTypeGet } from "../funcs/classesTypeGet.js";
import { classesTypeList } from "../funcs/classesTypeList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Type extends ClientSDK {
  /**
   * Get a class type
   *
   * @remarks
   * Get Class type details
   */
  async get(
    request: operations.GetClassTypeRequest,
    options?: RequestOptions,
  ): Promise<operations.GetClassTypeResponseBody> {
    return unwrapAsync(classesTypeGet(
      this,
      request,
      options,
    ));
  }

  /**
   * List class types for the given gym
   *
   * @remarks
   * Get Class type details
   */
  async list(
    request: operations.ListClassTypesRequest,
    options?: RequestOptions,
  ): Promise<operations.ListClassTypesResponseBody> {
    return unwrapAsync(classesTypeList(
      this,
      request,
      options,
    ));
  }
}
