workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    PushPress-OAS:
        inputs:
            - location: https://api.pushpressdev.com/platform/docs/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/speakeasy-sdks/pushpress-typescript-sdk/refs/heads/main/.speakeasy/speakeasy-modifications-overlay.yaml
            - location: https://raw.githubusercontent.com/speakeasy-sdks/pushpress-typescript-sdk/refs/heads/main/.speakeasy/speakeasy-suggest-error-types.yaml
        registry:
            location: registry.speakeasyapi.dev/pushpress/pushpress/push-press-oas
targets:
    push-press:
        target: typescript
        source: PushPress-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/pushpress/pushpress/push-press-oas-typescript-code-samples
            blocking: false
