/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateWebhookGlobals = {
  companyId?: string | undefined;
};

export const EventTypes2 = {
  AppointmentScheduled: "appointment.scheduled",
  AppointmentRescheduled: "appointment.rescheduled",
  AppointmentNoshowed: "appointment.noshowed",
  AppointmentCanceled: "appointment.canceled",
  CheckinCreated: "checkin.created",
  CheckinUpdated: "checkin.updated",
  CheckinDeleted: "checkin.deleted",
  ClassCanceled: "class.canceled",
  CustomerCreated: "customer.created",
  CustomerDetailsChanged: "customer.details.changed",
  CustomerStatusChanged: "customer.status.changed",
  CustomerDeleted: "customer.deleted",
  EnrollmentCreated: "enrollment.created",
  EnrollmentStatusChanged: "enrollment.status.changed",
  EnrollmentDeleted: "enrollment.deleted",
  MemberappUpdated: "memberapp.updated",
  ReservationCreated: "reservation.created",
  ReservationWaitlisted: "reservation.waitlisted",
  ReservationCanceled: "reservation.canceled",
  ReservationNoshowed: "reservation.noshowed",
} as const;
export type EventTypes2 = ClosedEnum<typeof EventTypes2>;

export const EventTypes1 = {
  AppInstalled: "app.installed",
  AppUninstalled: "app.uninstalled",
} as const;
export type EventTypes1 = ClosedEnum<typeof EventTypes1>;

/**
 * Webhooks registration must either apply to a set application events (e.g app.installed, app.uninstalled) or to customer events
 */
export type EventTypes = Array<EventTypes1> | Array<EventTypes2>;

export type CreateWebhookRequestBody = {
  /**
   * Webhooks for application lifecycle events must be created with an app ID
   */
  appId?: string | undefined;
  /**
   * The URL to send the webhook to
   */
  url: string;
  /**
   * Webhooks registration must either apply to a set application events (e.g app.installed, app.uninstalled) or to customer events
   */
  eventTypes: Array<EventTypes1> | Array<EventTypes2>;
};

export type CreateWebhookRequest = {
  /**
   * When using multitenant API keys, specify the company
   */
  companyId?: string | undefined;
  requestBody: CreateWebhookRequestBody;
};

export const CreateWebhookEventTypes = {
  AppointmentScheduled: "appointment.scheduled",
  AppointmentRescheduled: "appointment.rescheduled",
  AppointmentNoshowed: "appointment.noshowed",
  AppointmentCanceled: "appointment.canceled",
  CheckinCreated: "checkin.created",
  CheckinUpdated: "checkin.updated",
  CheckinDeleted: "checkin.deleted",
  ClassCanceled: "class.canceled",
  CustomerCreated: "customer.created",
  CustomerDetailsChanged: "customer.details.changed",
  CustomerStatusChanged: "customer.status.changed",
  CustomerDeleted: "customer.deleted",
  EnrollmentCreated: "enrollment.created",
  EnrollmentStatusChanged: "enrollment.status.changed",
  EnrollmentDeleted: "enrollment.deleted",
  MemberappUpdated: "memberapp.updated",
  ReservationCreated: "reservation.created",
  ReservationWaitlisted: "reservation.waitlisted",
  ReservationCanceled: "reservation.canceled",
  ReservationNoshowed: "reservation.noshowed",
  AppInstalled: "app.installed",
  AppUninstalled: "app.uninstalled",
} as const;
export type CreateWebhookEventTypes = ClosedEnum<
  typeof CreateWebhookEventTypes
>;

/**
 * Default Response
 */
export type CreateWebhookResponseBody = {
  /**
   * A unique identifier for the webhook
   */
  id: string;
  /**
   * The endpoint URL that will receive the webhook payloads
   */
  url: string;
  /**
   * The app ID with which application lifecyle event types (e.g. app.installed) are associated
   */
  appId?: string | undefined;
  /**
   * A list of event types that the webhook is subscribed to
   */
  eventTypes: Array<CreateWebhookEventTypes>;
  /**
   * Indicates whether the webhook is currently active and receiving events
   */
  active?: boolean | undefined;
  /**
   * A secret key used to sign the webhook payloads for security purposes
   */
  signingSecret: string;
};

/** @internal */
export const CreateWebhookGlobals$inboundSchema: z.ZodType<
  CreateWebhookGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "company-id": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
  });
});
/** @internal */
export type CreateWebhookGlobals$Outbound = {
  "company-id"?: string | undefined;
};

/** @internal */
export const CreateWebhookGlobals$outboundSchema: z.ZodType<
  CreateWebhookGlobals$Outbound,
  z.ZodTypeDef,
  CreateWebhookGlobals
> = z.object({
  companyId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
  });
});

export function createWebhookGlobalsToJSON(
  createWebhookGlobals: CreateWebhookGlobals,
): string {
  return JSON.stringify(
    CreateWebhookGlobals$outboundSchema.parse(createWebhookGlobals),
  );
}
export function createWebhookGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookGlobals' from JSON`,
  );
}

/** @internal */
export const EventTypes2$inboundSchema: z.ZodNativeEnum<typeof EventTypes2> = z
  .nativeEnum(EventTypes2);
/** @internal */
export const EventTypes2$outboundSchema: z.ZodNativeEnum<typeof EventTypes2> =
  EventTypes2$inboundSchema;

/** @internal */
export const EventTypes1$inboundSchema: z.ZodNativeEnum<typeof EventTypes1> = z
  .nativeEnum(EventTypes1);
/** @internal */
export const EventTypes1$outboundSchema: z.ZodNativeEnum<typeof EventTypes1> =
  EventTypes1$inboundSchema;

/** @internal */
export const EventTypes$inboundSchema: z.ZodType<
  EventTypes,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(EventTypes1$inboundSchema),
  z.array(EventTypes2$inboundSchema),
]);
/** @internal */
export type EventTypes$Outbound = Array<string> | Array<string>;

/** @internal */
export const EventTypes$outboundSchema: z.ZodType<
  EventTypes$Outbound,
  z.ZodTypeDef,
  EventTypes
> = z.union([
  z.array(EventTypes1$outboundSchema),
  z.array(EventTypes2$outboundSchema),
]);

export function eventTypesToJSON(eventTypes: EventTypes): string {
  return JSON.stringify(EventTypes$outboundSchema.parse(eventTypes));
}
export function eventTypesFromJSON(
  jsonString: string,
): SafeParseResult<EventTypes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventTypes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventTypes' from JSON`,
  );
}

/** @internal */
export const CreateWebhookRequestBody$inboundSchema: z.ZodType<
  CreateWebhookRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appId: z.string().optional(),
  url: z.string(),
  eventTypes: z.union([
    z.array(EventTypes1$inboundSchema),
    z.array(EventTypes2$inboundSchema),
  ]),
});
/** @internal */
export type CreateWebhookRequestBody$Outbound = {
  appId?: string | undefined;
  url: string;
  eventTypes: Array<string> | Array<string>;
};

/** @internal */
export const CreateWebhookRequestBody$outboundSchema: z.ZodType<
  CreateWebhookRequestBody$Outbound,
  z.ZodTypeDef,
  CreateWebhookRequestBody
> = z.object({
  appId: z.string().optional(),
  url: z.string(),
  eventTypes: z.union([
    z.array(EventTypes1$outboundSchema),
    z.array(EventTypes2$outboundSchema),
  ]),
});

export function createWebhookRequestBodyToJSON(
  createWebhookRequestBody: CreateWebhookRequestBody,
): string {
  return JSON.stringify(
    CreateWebhookRequestBody$outboundSchema.parse(createWebhookRequestBody),
  );
}
export function createWebhookRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateWebhookRequest$inboundSchema: z.ZodType<
  CreateWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "company-id": z.string().optional(),
  RequestBody: z.lazy(() => CreateWebhookRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type CreateWebhookRequest$Outbound = {
  "company-id"?: string | undefined;
  RequestBody: CreateWebhookRequestBody$Outbound;
};

/** @internal */
export const CreateWebhookRequest$outboundSchema: z.ZodType<
  CreateWebhookRequest$Outbound,
  z.ZodTypeDef,
  CreateWebhookRequest
> = z.object({
  companyId: z.string().optional(),
  requestBody: z.lazy(() => CreateWebhookRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
    requestBody: "RequestBody",
  });
});

export function createWebhookRequestToJSON(
  createWebhookRequest: CreateWebhookRequest,
): string {
  return JSON.stringify(
    CreateWebhookRequest$outboundSchema.parse(createWebhookRequest),
  );
}
export function createWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookRequest' from JSON`,
  );
}

/** @internal */
export const CreateWebhookEventTypes$inboundSchema: z.ZodNativeEnum<
  typeof CreateWebhookEventTypes
> = z.nativeEnum(CreateWebhookEventTypes);
/** @internal */
export const CreateWebhookEventTypes$outboundSchema: z.ZodNativeEnum<
  typeof CreateWebhookEventTypes
> = CreateWebhookEventTypes$inboundSchema;

/** @internal */
export const CreateWebhookResponseBody$inboundSchema: z.ZodType<
  CreateWebhookResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  url: z.string(),
  appId: z.string().optional(),
  eventTypes: z.array(CreateWebhookEventTypes$inboundSchema),
  active: z.boolean().default(true),
  signingSecret: z.string(),
});
/** @internal */
export type CreateWebhookResponseBody$Outbound = {
  id: string;
  url: string;
  appId?: string | undefined;
  eventTypes: Array<string>;
  active: boolean;
  signingSecret: string;
};

/** @internal */
export const CreateWebhookResponseBody$outboundSchema: z.ZodType<
  CreateWebhookResponseBody$Outbound,
  z.ZodTypeDef,
  CreateWebhookResponseBody
> = z.object({
  id: z.string(),
  url: z.string(),
  appId: z.string().optional(),
  eventTypes: z.array(CreateWebhookEventTypes$outboundSchema),
  active: z.boolean().default(true),
  signingSecret: z.string(),
});

export function createWebhookResponseBodyToJSON(
  createWebhookResponseBody: CreateWebhookResponseBody,
): string {
  return JSON.stringify(
    CreateWebhookResponseBody$outboundSchema.parse(createWebhookResponseBody),
  );
}
export function createWebhookResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookResponseBody' from JSON`,
  );
}
