/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteApiKeyRequest = {
  keyId: string;
};

/** @internal */
export const DeleteApiKeyRequest$inboundSchema: z.ZodType<
  DeleteApiKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  key_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "key_id": "keyId",
  });
});

/** @internal */
export type DeleteApiKeyRequest$Outbound = {
  key_id: string;
};

/** @internal */
export const DeleteApiKeyRequest$outboundSchema: z.ZodType<
  DeleteApiKeyRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiKeyRequest
> = z.object({
  keyId: z.string(),
}).transform((v) => {
  return remap$(v, {
    keyId: "key_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiKeyRequest$ {
  /** @deprecated use `DeleteApiKeyRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiKeyRequest$inboundSchema;
  /** @deprecated use `DeleteApiKeyRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiKeyRequest$outboundSchema;
  /** @deprecated use `DeleteApiKeyRequest$Outbound` instead. */
  export type Outbound = DeleteApiKeyRequest$Outbound;
}
