/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetAppInstallRequest = {
  appId: string;
  installId: string;
};

/** @internal */
export const GetAppInstallRequest$inboundSchema: z.ZodType<
  GetAppInstallRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app_id: z.string(),
  install_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "app_id": "appId",
    "install_id": "installId",
  });
});

/** @internal */
export type GetAppInstallRequest$Outbound = {
  app_id: string;
  install_id: string;
};

/** @internal */
export const GetAppInstallRequest$outboundSchema: z.ZodType<
  GetAppInstallRequest$Outbound,
  z.ZodTypeDef,
  GetAppInstallRequest
> = z.object({
  appId: z.string(),
  installId: z.string(),
}).transform((v) => {
  return remap$(v, {
    appId: "app_id",
    installId: "install_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAppInstallRequest$ {
  /** @deprecated use `GetAppInstallRequest$inboundSchema` instead. */
  export const inboundSchema = GetAppInstallRequest$inboundSchema;
  /** @deprecated use `GetAppInstallRequest$outboundSchema` instead. */
  export const outboundSchema = GetAppInstallRequest$outboundSchema;
  /** @deprecated use `GetAppInstallRequest$Outbound` instead. */
  export type Outbound = GetAppInstallRequest$Outbound;
}
