/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAppointmentCheckinGlobals = {
  companyId?: string | undefined;
};

export type GetAppointmentCheckinRequest = {
  uuid: string;
  /**
   * When using multitenant API keys, specify the company
   */
  companyId?: string | undefined;
};

/** @internal */
export const GetAppointmentCheckinGlobals$inboundSchema: z.ZodType<
  GetAppointmentCheckinGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "company-id": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
  });
});

/** @internal */
export type GetAppointmentCheckinGlobals$Outbound = {
  "company-id"?: string | undefined;
};

/** @internal */
export const GetAppointmentCheckinGlobals$outboundSchema: z.ZodType<
  GetAppointmentCheckinGlobals$Outbound,
  z.ZodTypeDef,
  GetAppointmentCheckinGlobals
> = z.object({
  companyId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAppointmentCheckinGlobals$ {
  /** @deprecated use `GetAppointmentCheckinGlobals$inboundSchema` instead. */
  export const inboundSchema = GetAppointmentCheckinGlobals$inboundSchema;
  /** @deprecated use `GetAppointmentCheckinGlobals$outboundSchema` instead. */
  export const outboundSchema = GetAppointmentCheckinGlobals$outboundSchema;
  /** @deprecated use `GetAppointmentCheckinGlobals$Outbound` instead. */
  export type Outbound = GetAppointmentCheckinGlobals$Outbound;
}

export function getAppointmentCheckinGlobalsToJSON(
  getAppointmentCheckinGlobals: GetAppointmentCheckinGlobals,
): string {
  return JSON.stringify(
    GetAppointmentCheckinGlobals$outboundSchema.parse(
      getAppointmentCheckinGlobals,
    ),
  );
}

export function getAppointmentCheckinGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetAppointmentCheckinGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAppointmentCheckinGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAppointmentCheckinGlobals' from JSON`,
  );
}

/** @internal */
export const GetAppointmentCheckinRequest$inboundSchema: z.ZodType<
  GetAppointmentCheckinRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  "company-id": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
  });
});

/** @internal */
export type GetAppointmentCheckinRequest$Outbound = {
  uuid: string;
  "company-id"?: string | undefined;
};

/** @internal */
export const GetAppointmentCheckinRequest$outboundSchema: z.ZodType<
  GetAppointmentCheckinRequest$Outbound,
  z.ZodTypeDef,
  GetAppointmentCheckinRequest
> = z.object({
  uuid: z.string(),
  companyId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAppointmentCheckinRequest$ {
  /** @deprecated use `GetAppointmentCheckinRequest$inboundSchema` instead. */
  export const inboundSchema = GetAppointmentCheckinRequest$inboundSchema;
  /** @deprecated use `GetAppointmentCheckinRequest$outboundSchema` instead. */
  export const outboundSchema = GetAppointmentCheckinRequest$outboundSchema;
  /** @deprecated use `GetAppointmentCheckinRequest$Outbound` instead. */
  export type Outbound = GetAppointmentCheckinRequest$Outbound;
}

export function getAppointmentCheckinRequestToJSON(
  getAppointmentCheckinRequest: GetAppointmentCheckinRequest,
): string {
  return JSON.stringify(
    GetAppointmentCheckinRequest$outboundSchema.parse(
      getAppointmentCheckinRequest,
    ),
  );
}

export function getAppointmentCheckinRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAppointmentCheckinRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAppointmentCheckinRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAppointmentCheckinRequest' from JSON`,
  );
}
