/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetClassCheckinRequest = {
  uuid: string;
  companyId?: any | undefined;
};

/** @internal */
export const GetClassCheckinRequest$inboundSchema: z.ZodType<
  GetClassCheckinRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  "company-id": z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
  });
});

/** @internal */
export type GetClassCheckinRequest$Outbound = {
  uuid: string;
  "company-id"?: any | undefined;
};

/** @internal */
export const GetClassCheckinRequest$outboundSchema: z.ZodType<
  GetClassCheckinRequest$Outbound,
  z.ZodTypeDef,
  GetClassCheckinRequest
> = z.object({
  uuid: z.string(),
  companyId: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetClassCheckinRequest$ {
  /** @deprecated use `GetClassCheckinRequest$inboundSchema` instead. */
  export const inboundSchema = GetClassCheckinRequest$inboundSchema;
  /** @deprecated use `GetClassCheckinRequest$outboundSchema` instead. */
  export const outboundSchema = GetClassCheckinRequest$outboundSchema;
  /** @deprecated use `GetClassCheckinRequest$Outbound` instead. */
  export type Outbound = GetClassCheckinRequest$Outbound;
}
