/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetEventCheckinRequest = {
  uuid: string;
  companyId?: any | undefined;
};

/** @internal */
export const GetEventCheckinRequest$inboundSchema: z.ZodType<
  GetEventCheckinRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  companyId: z.any().optional(),
});

/** @internal */
export type GetEventCheckinRequest$Outbound = {
  uuid: string;
  companyId?: any | undefined;
};

/** @internal */
export const GetEventCheckinRequest$outboundSchema: z.ZodType<
  GetEventCheckinRequest$Outbound,
  z.ZodTypeDef,
  GetEventCheckinRequest
> = z.object({
  uuid: z.string(),
  companyId: z.any().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetEventCheckinRequest$ {
  /** @deprecated use `GetEventCheckinRequest$inboundSchema` instead. */
  export const inboundSchema = GetEventCheckinRequest$inboundSchema;
  /** @deprecated use `GetEventCheckinRequest$outboundSchema` instead. */
  export const outboundSchema = GetEventCheckinRequest$outboundSchema;
  /** @deprecated use `GetEventCheckinRequest$Outbound` instead. */
  export type Outbound = GetEventCheckinRequest$Outbound;
}
