/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ListCompaniesRequest = {
  page?: number | undefined;
  limit?: number | undefined;
};

/**
 * A paginated response containing a list of companies
 */
export type ListCompaniesResponseBody = {
  data: Array<components.Company>;
};

export type ListCompaniesResponse = {
  result: ListCompaniesResponseBody;
};

/** @internal */
export const ListCompaniesRequest$inboundSchema: z.ZodType<
  ListCompaniesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
});

/** @internal */
export type ListCompaniesRequest$Outbound = {
  page: number;
  limit: number;
};

/** @internal */
export const ListCompaniesRequest$outboundSchema: z.ZodType<
  ListCompaniesRequest$Outbound,
  z.ZodTypeDef,
  ListCompaniesRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCompaniesRequest$ {
  /** @deprecated use `ListCompaniesRequest$inboundSchema` instead. */
  export const inboundSchema = ListCompaniesRequest$inboundSchema;
  /** @deprecated use `ListCompaniesRequest$outboundSchema` instead. */
  export const outboundSchema = ListCompaniesRequest$outboundSchema;
  /** @deprecated use `ListCompaniesRequest$Outbound` instead. */
  export type Outbound = ListCompaniesRequest$Outbound;
}

/** @internal */
export const ListCompaniesResponseBody$inboundSchema: z.ZodType<
  ListCompaniesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(components.Company$inboundSchema),
});

/** @internal */
export type ListCompaniesResponseBody$Outbound = {
  data: Array<components.Company$Outbound>;
};

/** @internal */
export const ListCompaniesResponseBody$outboundSchema: z.ZodType<
  ListCompaniesResponseBody$Outbound,
  z.ZodTypeDef,
  ListCompaniesResponseBody
> = z.object({
  data: z.array(components.Company$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCompaniesResponseBody$ {
  /** @deprecated use `ListCompaniesResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListCompaniesResponseBody$inboundSchema;
  /** @deprecated use `ListCompaniesResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListCompaniesResponseBody$outboundSchema;
  /** @deprecated use `ListCompaniesResponseBody$Outbound` instead. */
  export type Outbound = ListCompaniesResponseBody$Outbound;
}

/** @internal */
export const ListCompaniesResponse$inboundSchema: z.ZodType<
  ListCompaniesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListCompaniesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListCompaniesResponse$Outbound = {
  Result: ListCompaniesResponseBody$Outbound;
};

/** @internal */
export const ListCompaniesResponse$outboundSchema: z.ZodType<
  ListCompaniesResponse$Outbound,
  z.ZodTypeDef,
  ListCompaniesResponse
> = z.object({
  result: z.lazy(() => ListCompaniesResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCompaniesResponse$ {
  /** @deprecated use `ListCompaniesResponse$inboundSchema` instead. */
  export const inboundSchema = ListCompaniesResponse$inboundSchema;
  /** @deprecated use `ListCompaniesResponse$outboundSchema` instead. */
  export const outboundSchema = ListCompaniesResponse$outboundSchema;
  /** @deprecated use `ListCompaniesResponse$Outbound` instead. */
  export type Outbound = ListCompaniesResponse$Outbound;
}
