/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListClassCheckinsGlobals = {
  companyId?: string | undefined;
};

export type ListClassCheckinsRequest = {
  /**
   * page number
   */
  page?: number | undefined;
  /**
   * limit
   */
  limit?: number | undefined;
  customer?: string | undefined;
  /**
   * Get all checkins before this unix timestamp (seconds)
   */
  before?: number | undefined;
  /**
   * Get all checkins after this unix timestamp (seconds)
   */
  after?: number | undefined;
  /**
   * When using multitenant API keys, specify the company
   */
  companyId?: string | undefined;
};

export type ListClassCheckinsData = {
  resultArray: Array<components.ClassCheckin>;
};

/**
 * Default Response
 */
export type ListClassCheckinsResponseBody = {
  data: ListClassCheckinsData;
};

export type ListClassCheckinsResponse = {
  result: ListClassCheckinsResponseBody;
};

/** @internal */
export const ListClassCheckinsGlobals$inboundSchema: z.ZodType<
  ListClassCheckinsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "company-id": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
  });
});

/** @internal */
export type ListClassCheckinsGlobals$Outbound = {
  "company-id"?: string | undefined;
};

/** @internal */
export const ListClassCheckinsGlobals$outboundSchema: z.ZodType<
  ListClassCheckinsGlobals$Outbound,
  z.ZodTypeDef,
  ListClassCheckinsGlobals
> = z.object({
  companyId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListClassCheckinsGlobals$ {
  /** @deprecated use `ListClassCheckinsGlobals$inboundSchema` instead. */
  export const inboundSchema = ListClassCheckinsGlobals$inboundSchema;
  /** @deprecated use `ListClassCheckinsGlobals$outboundSchema` instead. */
  export const outboundSchema = ListClassCheckinsGlobals$outboundSchema;
  /** @deprecated use `ListClassCheckinsGlobals$Outbound` instead. */
  export type Outbound = ListClassCheckinsGlobals$Outbound;
}

export function listClassCheckinsGlobalsToJSON(
  listClassCheckinsGlobals: ListClassCheckinsGlobals,
): string {
  return JSON.stringify(
    ListClassCheckinsGlobals$outboundSchema.parse(listClassCheckinsGlobals),
  );
}

export function listClassCheckinsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListClassCheckinsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassCheckinsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassCheckinsGlobals' from JSON`,
  );
}

/** @internal */
export const ListClassCheckinsRequest$inboundSchema: z.ZodType<
  ListClassCheckinsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  customer: z.string().optional(),
  before: z.number().optional(),
  after: z.number().optional(),
  "company-id": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
  });
});

/** @internal */
export type ListClassCheckinsRequest$Outbound = {
  page: number;
  limit: number;
  customer?: string | undefined;
  before?: number | undefined;
  after?: number | undefined;
  "company-id"?: string | undefined;
};

/** @internal */
export const ListClassCheckinsRequest$outboundSchema: z.ZodType<
  ListClassCheckinsRequest$Outbound,
  z.ZodTypeDef,
  ListClassCheckinsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  customer: z.string().optional(),
  before: z.number().optional(),
  after: z.number().optional(),
  companyId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListClassCheckinsRequest$ {
  /** @deprecated use `ListClassCheckinsRequest$inboundSchema` instead. */
  export const inboundSchema = ListClassCheckinsRequest$inboundSchema;
  /** @deprecated use `ListClassCheckinsRequest$outboundSchema` instead. */
  export const outboundSchema = ListClassCheckinsRequest$outboundSchema;
  /** @deprecated use `ListClassCheckinsRequest$Outbound` instead. */
  export type Outbound = ListClassCheckinsRequest$Outbound;
}

export function listClassCheckinsRequestToJSON(
  listClassCheckinsRequest: ListClassCheckinsRequest,
): string {
  return JSON.stringify(
    ListClassCheckinsRequest$outboundSchema.parse(listClassCheckinsRequest),
  );
}

export function listClassCheckinsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListClassCheckinsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassCheckinsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassCheckinsRequest' from JSON`,
  );
}

/** @internal */
export const ListClassCheckinsData$inboundSchema: z.ZodType<
  ListClassCheckinsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultArray: z.array(components.ClassCheckin$inboundSchema),
});

/** @internal */
export type ListClassCheckinsData$Outbound = {
  resultArray: Array<components.ClassCheckin$Outbound>;
};

/** @internal */
export const ListClassCheckinsData$outboundSchema: z.ZodType<
  ListClassCheckinsData$Outbound,
  z.ZodTypeDef,
  ListClassCheckinsData
> = z.object({
  resultArray: z.array(components.ClassCheckin$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListClassCheckinsData$ {
  /** @deprecated use `ListClassCheckinsData$inboundSchema` instead. */
  export const inboundSchema = ListClassCheckinsData$inboundSchema;
  /** @deprecated use `ListClassCheckinsData$outboundSchema` instead. */
  export const outboundSchema = ListClassCheckinsData$outboundSchema;
  /** @deprecated use `ListClassCheckinsData$Outbound` instead. */
  export type Outbound = ListClassCheckinsData$Outbound;
}

export function listClassCheckinsDataToJSON(
  listClassCheckinsData: ListClassCheckinsData,
): string {
  return JSON.stringify(
    ListClassCheckinsData$outboundSchema.parse(listClassCheckinsData),
  );
}

export function listClassCheckinsDataFromJSON(
  jsonString: string,
): SafeParseResult<ListClassCheckinsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassCheckinsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassCheckinsData' from JSON`,
  );
}

/** @internal */
export const ListClassCheckinsResponseBody$inboundSchema: z.ZodType<
  ListClassCheckinsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ListClassCheckinsData$inboundSchema),
});

/** @internal */
export type ListClassCheckinsResponseBody$Outbound = {
  data: ListClassCheckinsData$Outbound;
};

/** @internal */
export const ListClassCheckinsResponseBody$outboundSchema: z.ZodType<
  ListClassCheckinsResponseBody$Outbound,
  z.ZodTypeDef,
  ListClassCheckinsResponseBody
> = z.object({
  data: z.lazy(() => ListClassCheckinsData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListClassCheckinsResponseBody$ {
  /** @deprecated use `ListClassCheckinsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListClassCheckinsResponseBody$inboundSchema;
  /** @deprecated use `ListClassCheckinsResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListClassCheckinsResponseBody$outboundSchema;
  /** @deprecated use `ListClassCheckinsResponseBody$Outbound` instead. */
  export type Outbound = ListClassCheckinsResponseBody$Outbound;
}

export function listClassCheckinsResponseBodyToJSON(
  listClassCheckinsResponseBody: ListClassCheckinsResponseBody,
): string {
  return JSON.stringify(
    ListClassCheckinsResponseBody$outboundSchema.parse(
      listClassCheckinsResponseBody,
    ),
  );
}

export function listClassCheckinsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListClassCheckinsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassCheckinsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassCheckinsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListClassCheckinsResponse$inboundSchema: z.ZodType<
  ListClassCheckinsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListClassCheckinsResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListClassCheckinsResponse$Outbound = {
  Result: ListClassCheckinsResponseBody$Outbound;
};

/** @internal */
export const ListClassCheckinsResponse$outboundSchema: z.ZodType<
  ListClassCheckinsResponse$Outbound,
  z.ZodTypeDef,
  ListClassCheckinsResponse
> = z.object({
  result: z.lazy(() => ListClassCheckinsResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListClassCheckinsResponse$ {
  /** @deprecated use `ListClassCheckinsResponse$inboundSchema` instead. */
  export const inboundSchema = ListClassCheckinsResponse$inboundSchema;
  /** @deprecated use `ListClassCheckinsResponse$outboundSchema` instead. */
  export const outboundSchema = ListClassCheckinsResponse$outboundSchema;
  /** @deprecated use `ListClassCheckinsResponse$Outbound` instead. */
  export type Outbound = ListClassCheckinsResponse$Outbound;
}

export function listClassCheckinsResponseToJSON(
  listClassCheckinsResponse: ListClassCheckinsResponse,
): string {
  return JSON.stringify(
    ListClassCheckinsResponse$outboundSchema.parse(listClassCheckinsResponse),
  );
}

export function listClassCheckinsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListClassCheckinsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassCheckinsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassCheckinsResponse' from JSON`,
  );
}
