/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListClassesGlobals = {
  companyId?: string | undefined;
};

/**
 * Some events require an invitation for signup, most invites and all classes are open registration
 */
export const Access = {
  InviteOnly: "invite_only",
  Open: "open",
} as const;
/**
 * Some events require an invitation for signup, most invites and all classes are open registration
 */
export type Access = ClosedEnum<typeof Access>;

/**
 * sort classes by start timestamp
 */
export const Order = {
  Ascending: "ascending",
  Descending: "descending",
} as const;
/**
 * sort classes by start timestamp
 */
export type Order = ClosedEnum<typeof Order>;

export type ListClassesRequest = {
  /**
   * page number
   */
  page?: number | undefined;
  /**
   * limit
   */
  limit?: number | undefined;
  /**
   * Filter by classes that start after this timestamp (Unix Seconds)
   */
  startsAfter?: number | undefined;
  /**
   * Some events require an invitation for signup, most invites and all classes are open registration
   */
  access?: Access | undefined;
  /**
   * sort classes by start timestamp
   */
  order?: Order | undefined;
  /**
   * When using multitenant API keys, specify the company
   */
  companyId?: string | undefined;
};

export type ListClassesData = {
  resultArray: Array<components.Class>;
};

/**
 * Default Response
 */
export type ListClassesResponseBody = {
  data: ListClassesData;
};

export type ListClassesResponse = {
  result: ListClassesResponseBody;
};

/** @internal */
export const ListClassesGlobals$inboundSchema: z.ZodType<
  ListClassesGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "company-id": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
  });
});
/** @internal */
export type ListClassesGlobals$Outbound = {
  "company-id"?: string | undefined;
};

/** @internal */
export const ListClassesGlobals$outboundSchema: z.ZodType<
  ListClassesGlobals$Outbound,
  z.ZodTypeDef,
  ListClassesGlobals
> = z.object({
  companyId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
  });
});

export function listClassesGlobalsToJSON(
  listClassesGlobals: ListClassesGlobals,
): string {
  return JSON.stringify(
    ListClassesGlobals$outboundSchema.parse(listClassesGlobals),
  );
}
export function listClassesGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListClassesGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassesGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassesGlobals' from JSON`,
  );
}

/** @internal */
export const Access$inboundSchema: z.ZodNativeEnum<typeof Access> = z
  .nativeEnum(Access);
/** @internal */
export const Access$outboundSchema: z.ZodNativeEnum<typeof Access> =
  Access$inboundSchema;

/** @internal */
export const Order$inboundSchema: z.ZodNativeEnum<typeof Order> = z.nativeEnum(
  Order,
);
/** @internal */
export const Order$outboundSchema: z.ZodNativeEnum<typeof Order> =
  Order$inboundSchema;

/** @internal */
export const ListClassesRequest$inboundSchema: z.ZodType<
  ListClassesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  startsAfter: z.number().optional(),
  access: Access$inboundSchema.optional(),
  order: Order$inboundSchema.default("ascending"),
  "company-id": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "company-id": "companyId",
  });
});
/** @internal */
export type ListClassesRequest$Outbound = {
  page: number;
  limit: number;
  startsAfter?: number | undefined;
  access?: string | undefined;
  order: string;
  "company-id"?: string | undefined;
};

/** @internal */
export const ListClassesRequest$outboundSchema: z.ZodType<
  ListClassesRequest$Outbound,
  z.ZodTypeDef,
  ListClassesRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  startsAfter: z.number().optional(),
  access: Access$outboundSchema.optional(),
  order: Order$outboundSchema.default("ascending"),
  companyId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company-id",
  });
});

export function listClassesRequestToJSON(
  listClassesRequest: ListClassesRequest,
): string {
  return JSON.stringify(
    ListClassesRequest$outboundSchema.parse(listClassesRequest),
  );
}
export function listClassesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListClassesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassesRequest' from JSON`,
  );
}

/** @internal */
export const ListClassesData$inboundSchema: z.ZodType<
  ListClassesData,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultArray: z.array(components.Class$inboundSchema),
});
/** @internal */
export type ListClassesData$Outbound = {
  resultArray: Array<components.Class$Outbound>;
};

/** @internal */
export const ListClassesData$outboundSchema: z.ZodType<
  ListClassesData$Outbound,
  z.ZodTypeDef,
  ListClassesData
> = z.object({
  resultArray: z.array(components.Class$outboundSchema),
});

export function listClassesDataToJSON(
  listClassesData: ListClassesData,
): string {
  return JSON.stringify(ListClassesData$outboundSchema.parse(listClassesData));
}
export function listClassesDataFromJSON(
  jsonString: string,
): SafeParseResult<ListClassesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassesData' from JSON`,
  );
}

/** @internal */
export const ListClassesResponseBody$inboundSchema: z.ZodType<
  ListClassesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ListClassesData$inboundSchema),
});
/** @internal */
export type ListClassesResponseBody$Outbound = {
  data: ListClassesData$Outbound;
};

/** @internal */
export const ListClassesResponseBody$outboundSchema: z.ZodType<
  ListClassesResponseBody$Outbound,
  z.ZodTypeDef,
  ListClassesResponseBody
> = z.object({
  data: z.lazy(() => ListClassesData$outboundSchema),
});

export function listClassesResponseBodyToJSON(
  listClassesResponseBody: ListClassesResponseBody,
): string {
  return JSON.stringify(
    ListClassesResponseBody$outboundSchema.parse(listClassesResponseBody),
  );
}
export function listClassesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListClassesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListClassesResponse$inboundSchema: z.ZodType<
  ListClassesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListClassesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListClassesResponse$Outbound = {
  Result: ListClassesResponseBody$Outbound;
};

/** @internal */
export const ListClassesResponse$outboundSchema: z.ZodType<
  ListClassesResponse$Outbound,
  z.ZodTypeDef,
  ListClassesResponse
> = z.object({
  result: z.lazy(() => ListClassesResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listClassesResponseToJSON(
  listClassesResponse: ListClassesResponse,
): string {
  return JSON.stringify(
    ListClassesResponse$outboundSchema.parse(listClassesResponse),
  );
}
export function listClassesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListClassesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClassesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClassesResponse' from JSON`,
  );
}
