/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Type = {
  /**
   * name of the appointment type
   */
  name: string;
};

/**
 * Schema for representing a Regsitration for some scheduled event
 */
export type Appointment = {
  /**
   * unique identifier for the appointment
   */
  id: string;
  type: Type;
  /**
   * unique identifier for the company
   */
  companyId: string;
  /**
   * True when the appointment was canceled late
   */
  isLateCancel?: boolean | undefined;
  /**
   * unique identifier for the customer
   */
  customerId: string;
  /**
   * Unix timestamp for the start time of the appointment
   */
  startTimestamp: number;
  /**
   * unique identifier for the staff member, corresponding to a customer with a staff role
   */
  staffId: string;
};

/** @internal */
export const Type$inboundSchema: z.ZodType<Type, z.ZodTypeDef, unknown> = z
  .object({
    name: z.string(),
  });

/** @internal */
export type Type$Outbound = {
  name: string;
};

/** @internal */
export const Type$outboundSchema: z.ZodType<Type$Outbound, z.ZodTypeDef, Type> =
  z.object({
    name: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Type$ {
  /** @deprecated use `Type$inboundSchema` instead. */
  export const inboundSchema = Type$inboundSchema;
  /** @deprecated use `Type$outboundSchema` instead. */
  export const outboundSchema = Type$outboundSchema;
  /** @deprecated use `Type$Outbound` instead. */
  export type Outbound = Type$Outbound;
}

export function typeToJSON(type: Type): string {
  return JSON.stringify(Type$outboundSchema.parse(type));
}

export function typeFromJSON(
  jsonString: string,
): SafeParseResult<Type, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Type$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Type' from JSON`,
  );
}

/** @internal */
export const Appointment$inboundSchema: z.ZodType<
  Appointment,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.lazy(() => Type$inboundSchema),
  companyId: z.string(),
  isLateCancel: z.boolean().optional(),
  customerId: z.string(),
  startTimestamp: z.number(),
  staffId: z.string(),
});

/** @internal */
export type Appointment$Outbound = {
  id: string;
  type: Type$Outbound;
  companyId: string;
  isLateCancel?: boolean | undefined;
  customerId: string;
  startTimestamp: number;
  staffId: string;
};

/** @internal */
export const Appointment$outboundSchema: z.ZodType<
  Appointment$Outbound,
  z.ZodTypeDef,
  Appointment
> = z.object({
  id: z.string(),
  type: z.lazy(() => Type$outboundSchema),
  companyId: z.string(),
  isLateCancel: z.boolean().optional(),
  customerId: z.string(),
  startTimestamp: z.number(),
  staffId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Appointment$ {
  /** @deprecated use `Appointment$inboundSchema` instead. */
  export const inboundSchema = Appointment$inboundSchema;
  /** @deprecated use `Appointment$outboundSchema` instead. */
  export const outboundSchema = Appointment$outboundSchema;
  /** @deprecated use `Appointment$Outbound` instead. */
  export type Outbound = Appointment$Outbound;
}

export function appointmentToJSON(appointment: Appointment): string {
  return JSON.stringify(Appointment$outboundSchema.parse(appointment));
}

export function appointmentFromJSON(
  jsonString: string,
): SafeParseResult<Appointment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Appointment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Appointment' from JSON`,
  );
}
