/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppointmentCheckin,
  AppointmentCheckin$inboundSchema,
  AppointmentCheckin$Outbound,
  AppointmentCheckin$outboundSchema,
} from "./appointmentcheckin.js";
import {
  ClassCheckin,
  ClassCheckin$inboundSchema,
  ClassCheckin$Outbound,
  ClassCheckin$outboundSchema,
} from "./classcheckin.js";
import {
  EventCheckin,
  EventCheckin$inboundSchema,
  EventCheckin$Outbound,
  EventCheckin$outboundSchema,
} from "./eventcheckin.js";
import {
  OpenCheckin,
  OpenCheckin$inboundSchema,
  OpenCheckin$Outbound,
  OpenCheckin$outboundSchema,
} from "./opencheckin.js";

/**
 * Checkin for a class, event, appointment or an open facility
 */
export type Checkin =
  | ClassCheckin
  | AppointmentCheckin
  | EventCheckin
  | OpenCheckin;

/** @internal */
export const Checkin$inboundSchema: z.ZodType<Checkin, z.ZodTypeDef, unknown> =
  z.union([
    ClassCheckin$inboundSchema,
    AppointmentCheckin$inboundSchema,
    EventCheckin$inboundSchema,
    OpenCheckin$inboundSchema,
  ]);
/** @internal */
export type Checkin$Outbound =
  | ClassCheckin$Outbound
  | AppointmentCheckin$Outbound
  | EventCheckin$Outbound
  | OpenCheckin$Outbound;

/** @internal */
export const Checkin$outboundSchema: z.ZodType<
  Checkin$Outbound,
  z.ZodTypeDef,
  Checkin
> = z.union([
  ClassCheckin$outboundSchema,
  AppointmentCheckin$outboundSchema,
  EventCheckin$outboundSchema,
  OpenCheckin$outboundSchema,
]);

export function checkinToJSON(checkin: Checkin): string {
  return JSON.stringify(Checkin$outboundSchema.parse(checkin));
}
export function checkinFromJSON(
  jsonString: string,
): SafeParseResult<Checkin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Checkin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Checkin' from JSON`,
  );
}
