/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppointmentCheckin,
  AppointmentCheckin$inboundSchema,
  AppointmentCheckin$Outbound,
  AppointmentCheckin$outboundSchema,
} from "./appointmentcheckin.js";
import {
  ClassCheckin,
  ClassCheckin$inboundSchema,
  ClassCheckin$Outbound,
  ClassCheckin$outboundSchema,
} from "./classcheckin.js";
import {
  EventCheckin,
  EventCheckin$inboundSchema,
  EventCheckin$Outbound,
  EventCheckin$outboundSchema,
} from "./eventcheckin.js";

/**
 * Checkin for a class, event, or appointment
 */
export type Checkin = AppointmentCheckin | ClassCheckin | EventCheckin;

/** @internal */
export const Checkin$inboundSchema: z.ZodType<Checkin, z.ZodTypeDef, unknown> =
  z.union([
    AppointmentCheckin$inboundSchema,
    ClassCheckin$inboundSchema,
    EventCheckin$inboundSchema,
  ]);

/** @internal */
export type Checkin$Outbound =
  | AppointmentCheckin$Outbound
  | ClassCheckin$Outbound
  | EventCheckin$Outbound;

/** @internal */
export const Checkin$outboundSchema: z.ZodType<
  Checkin$Outbound,
  z.ZodTypeDef,
  Checkin
> = z.union([
  AppointmentCheckin$outboundSchema,
  ClassCheckin$outboundSchema,
  EventCheckin$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Checkin$ {
  /** @deprecated use `Checkin$inboundSchema` instead. */
  export const inboundSchema = Checkin$inboundSchema;
  /** @deprecated use `Checkin$outboundSchema` instead. */
  export const outboundSchema = Checkin$outboundSchema;
  /** @deprecated use `Checkin$Outbound` instead. */
  export type Outbound = Checkin$Outbound;
}

export function checkinToJSON(checkin: Checkin): string {
  return JSON.stringify(Checkin$outboundSchema.parse(checkin));
}

export function checkinFromJSON(
  jsonString: string,
): SafeParseResult<Checkin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Checkin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Checkin' from JSON`,
  );
}
